#!/bin/bash
# capture_decisions.sh
# Scans a file just written/edited by Claude for DECISION/ASSUMPTION/DEBT
# comments and appends new ones to .claude/cognitive_debt.md
#
# Called automatically by Claude Code PostToolUse hook

set -euo pipefail

FILE="${1:-}"
LOG=".claude/cognitive_debt.md"
NOW=$(date +"%Y-%m-%d %H:%M")

# Only process Python files
if [[ -z "$FILE" || ! "$FILE" =~ \.py$ ]]; then
  exit 0
fi

if [[ ! -f "$FILE" ]]; then
  exit 0
fi

# Bootstrap log if needed
if [[ ! -f "$LOG" ]]; then
  mkdir -p "$(dirname "$LOG")"
  cat > "$LOG" << 'EOF'
# Cognitive Debt Log

Auto-generated by `.claude/hooks/capture_decisions.sh`.
Captures DECISION / ASSUMPTION / DEBT / THRESHOLD comments from files Claude writes.

---

EOF
fi

# Match tagged comments
PATTERN="# (DECISION|ASSUMPTION NEEDED|ASSUMPTION|DEBT|THRESHOLD):"

FOUND=0
while IFS= read -r match; do
  LINE_NUM=$(echo "$match" | cut -d: -f1)
  CONTENT=$(echo "$match" | cut -d: -f2-)

  # Skip if this file:line already in the log
  if grep -qF "$FILE:$LINE_NUM" "$LOG" 2>/dev/null; then
    continue
  fi

  echo "$NOW | $FILE:$LINE_NUM |$CONTENT" >> "$LOG"
  FOUND=$((FOUND + 1))

done < <(grep -nE "$PATTERN" "$FILE" 2>/dev/null || true)

if [[ $FOUND -gt 0 ]]; then
  echo "Cognitive debt captured: $FOUND new item(s) from $FILE"
fi
